import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import { Toaster } from "@/components/ui/sonner"


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cyber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
        className={` `}
    >
      <body >
        <Header/>
        <main>
        {children}
      </main>
        <Footer/>
        <Toaster richColors position="bottom-right" />
        </body>
      
    </html>
  );
}
